// Generated by CoffeeScript 1.4.0
(function() {

  $(document).on("change", ".duns-btn", function(e) {
    var button, el;
    el = $(this);
    button = el.find("button");
    e.preventDefault();
    $(".duns-paths").addClass("hide");
    return $("." + el.val()).removeClass("hide");
  });

  $(document).on("mouseenter", ".helper-tooltip", function(e) {
    $(this).tooltip();
    return $(this).tooltip('show');
  });

  $(document).on("mouseleave", ".helper-tooltip", function(e) {
    return $(this).tooltip('hide');
  });

  $(document).on("mouseenter", ".helper-popover", function(e) {
    $(this).popover();
    return $(this).popover('show');
  });

  $(document).on("mouseleave", ".helper-popover", function(e) {
    return $(this).popover('hide');
  });

  $(document).on("ready", function() {
    return $("#contact-form").validate_sam({
      rules: {
        "fname": {
          required: true
        },
        "lname": {
          required: true
        },
        "phone": {
          required: true
        },
        "email": {
          required: true,
          email: true
        },
        "confirmemail": {
          required: true,
          equalTo: "#email"
        }
      },
      messages: {
        "confirmemail": {
          equalTo: "This must be the same as the previous email"
        }
      }
    });
  });

}).call(this);
